# Generated by Django 2.0.7 on 2021-06-10 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='ชื่อทีม')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('permissions', models.CharField(default='', max_length=50, verbose_name='สิทธิ์')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='ชื่อ')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='วันที่')),
                ('description', models.CharField(default='', max_length=100, verbose_name='รายละเอียด')),
                ('type', models.CharField(choices=[('deposite', 'deposite'), ('withdraw', 'withdraw'), ('transfer', 'transfer')], default='deposite', max_length=15)),
                ('amount', models.IntegerField(default=0, verbose_name='จำนวนเงิน')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='หลักฐาน')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.AllTeam')),
            ],
        ),
    ]
