# Generated by Django 2.0.7 on 2021-06-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allteam',
            name='names',
        ),
    ]
