# Generated by Django 2.0.7 on 2021-06-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allteam',
            old_name='names',
            new_name='test',
        ),
    ]
