# Generated by Django 2.0.7 on 2021-06-10 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteam',
            name='team_id',
        ),
        migrations.AddField(
            model_name='myteam',
            name='Member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myteam',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.AllTeam'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='permissions',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member')], max_length=10, verbose_name='สิทธิ์'),
        ),
    ]
