# Generated by Django 3.2.1 on 2021-05-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_transactions_redcord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='redcord',
            new_name='record',
        ),
    ]
