# Generated by Django 2.0.7 on 2021-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210611_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteam',
            name='test',
            field=models.CharField(default='', max_length=50, verbose_name='dd'),
        ),
    ]
