# Generated by Django 2.0.7 on 2021-06-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210611_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allteam',
            old_name='test',
            new_name='tests',
        ),
    ]
