# Generated by Django 2.0.7 on 2021-06-10 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210611_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteam',
            name='create_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
