# Generated by Django 2.0.7 on 2021-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210512_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='รายละเอียด'),
        ),
    ]
