# Generated by Django 2.0.7 on 2021-05-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Type',
            field=models.CharField(choices=[('deposite', 'deposite'), ('withdraw', 'withdraw')], default='deposite', max_length=15),
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
