# Generated by Django 2.0.7 on 2021-05-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210512_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
