# Generated by Django 2.0.7 on 2021-05-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_record_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Type',
            new_name='type',
        ),
    ]
