# Generated by Django 2.0.7 on 2021-05-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20210512_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('deposite', 'deposite'), ('withdraw', 'withdraw'), ('transfer', 'transfer')], default='deposite', max_length=15),
        ),
    ]
