# Generated by Django 2.0.7 on 2021-05-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20210512_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='จำนวนเงิน'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='ชื่อ'),
        ),
    ]
