# Generated by Django 2.0.7 on 2021-05-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20210520_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='Evidence/'),
        ),
    ]
