# Generated by Django 2.0.7 on 2021-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_record_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='Evidence/', verbose_name='หลักฐาน'),
        ),
    ]
