# Generated by Django 2.0.7 on 2021-05-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20210525_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='หลักฐาน'),
        ),
    ]
