# Generated by Django 2.0.7 on 2021-06-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_allteams_myteams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allteams',
        ),
        migrations.DeleteModel(
            name='myteams',
        ),
    ]
