# Generated by Django 2.0.7 on 2021-06-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_allteams_myteams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allteams',
            new_name='allteam',
        ),
        migrations.RenameModel(
            old_name='myteams',
            new_name='myteam',
        ),
    ]
