# Generated by Django 2.0.7 on 2021-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_allteam_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteam',
            name='create_by',
            field=models.CharField(default='', max_length=50, verbose_name='ผู้สร้าง'),
        ),
    ]
