# Generated by Django 2.0.7 on 2021-06-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_auto_20210609_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteam',
            name='create_by',
            field=models.CharField(max_length=50, verbose_name='auth.User'),
        ),
    ]
