# Generated by Django 2.0.7 on 2021-06-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_auto_20210610_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allteam',
            name='create_by',
        ),
    ]
