# Generated by Django 2.0.7 on 2021-06-09 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_remove_allteam_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteam',
            name='date_build',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้างทีม'),
        ),
    ]
