# Generated by Django 2.0.7 on 2021-06-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_auto_20210610_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allteam',
            name='date_build',
        ),
        migrations.RemoveField(
            model_name='myteam',
            name='date_join',
        ),
    ]
