# Generated by Django 2.0.7 on 2021-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_record_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='allteam',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
